services:
  # Static Site (완전 무료 / Always on)
  - type: web
    name: clover-wallet-app-web
    runtime: static
    
    # 환경 변수
    envVars:
      - key: FLUTTER_WEB_RENDER
        value: true
        
    # 자동 배포 설정
    autoDeploy: true
    
    # 빌드 설정
    buildCommand: ./render_build.sh
    staticPublishPath: build/web
    
    # 리전 (Static Site는 Global CDN 사용하므로 리전 설정 불필요/자동)
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
